[package]
name = "platformer-rust"
version = "0.1.0"
authors = ["Reza Hajianpour <reza.hajianpour@queensu.ca>"]
edition = "2018"

[dependencies]
sfml = "0.14.0"

[lib]
name = "engine"
path = "src/engine/lib.rs"

[[bin]]
name = "runtime"
path = "src/runtime/main.rs"
